export const environment = {
  production: true,
  baseUrl: 'https://localhost:7092/api',
  endpoint: 'Settings',
  resourceEndpoint: 'Resources',
  monitoringEndpoint: 'Monitorings',
  userLoginEndpoint: 'Authentications/UserLogin',
  moduleEndpoint: 'Modules',
  module: 'Modules',
  user: 'v1/Users',
  Group: 'v1/Groups',
  job: 'Jobs',
  projectFile: 'ProjectFile',
  Permission: 'Permission',
  Comment: 'comments',
  ticketEndpoint: 'Tickets',
  feature: 'Features',
  label: 'Labels',
};
